/**
 * 
 */
package gov.va.oit.vistaevolution.kernel.ws.xqalbutl.endpoints;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import gov.va.oit.vistaevolution.kernel.ws.xqalbutl.endpoints.interfaces.XQALBUTLAlertDatEndpoint;
import gov.va.oit.vistaevolution.kernel.ws.xqalbutl.model.XQALBUTLAlertDatRequest;
import gov.va.oit.vistaevolution.kernel.ws.xqalbutl.model.XQALBUTLAlertDatResponse;
import gov.va.oit.vistaevolution.utils.vistalink.EvolutionIT;
import gov.va.oit.vistaevolution.ws.faults.VistaWebServiceFault;

import java.util.ArrayList;

import org.apache.log4j.Logger;
import org.junit.After;
import org.junit.Before;
import org.junit.Ignore;
import org.junit.Test;

/**
 * @author Leisa Martella
 *
 */
/**
 * XU SOA AHIST
 *
 * This RPC returns information from the ALERT TRACKING file (#8992.1) for alerts with the 
 * XUAID input parameter as its alert ID.  
 *  
 * 
 * Input Variables	
 * 		XUAID:	(required) This is the value XUAID which is the alert identifier.  
 * 				It is passed to the routine or option which is run when the alert 
 * 				is selected.  It can also be obtained from a listing of all of the 
 * 				XUAIDs for a specified user and/or patient.
 * 
 * Response
 * 		Returns data descendent from the closed root passed in XURET.
 * 		The basic structure of the nodes is taken from the global for the
 * 		entry and can be seen in a global map of the ALERT TRACKING (#8992.1)
 * 		file.
 * 
 * 		array(0)="NO-ID;83194;3140107.141502^3140107.141502^NO-ID^^83194^1"
 * 		array(1)="Your task #6749088 stopped because of an error^^XQA^XUTMUTL"
 * 		array(2)=6749088
 * 		array(20,0)="^8992.11PA^1^1"
 * 		array(20,1,0)=83194
 * 		array(20,1,1,0)="^8992.111PA^1^1"
 * 		array(20,1,1,1,0)="1^^^3140107.141502"
 * 		array(20,1,1,"B",1,1)=""
 * 		array(20,"B",83194,1)=""
 * 
 */

public class XQALBUTLAlertDatIT extends EvolutionIT <XQALBUTLAlertDatEndpoint>{

	@SuppressWarnings("unused")
	private static final Logger LOG = Logger
			.getLogger(XQALBUTLAlertDatIT.class);

	@Override
	protected Class<XQALBUTLAlertDatEndpoint> getType() {
		return XQALBUTLAlertDatEndpoint.class;
	}
	
	private XQALBUTLAlertDatRequest request;
	private XQALBUTLAlertDatResponse response;

	@Before
	public void setUp() {
		request = new XQALBUTLAlertDatRequest();
	}

	@After
	public void tearDown() {
		request = null;
	}

	/** 
	 * Test Case #1
	 * 
	 * In this test case you will look for a specific alert by its alert identifier.  
	 *
	 * >S XURET="",XUAID="LA7-MESSAGE-416570;.5;3030226.111106"
	 * 
	 * >D ALERTR^XUSOAR(XURET,XUAID)
	 * 
	 * >ZW XURET
	 * XURET(.01)="LA7-MESSAGE-416570;.5;3030226.111106"
	 * XURET(.01,"NAME")=""
	 * XURET(.02)="3030226.111106^FEB 26, 2003@11:11:06"
	 * XURET(.02,"DATE CREATED")=""
	 * XURET(.03)="LA7-MESSAGE-416570"
	 * XURET(.03,"PKG ID")=""
	 * XURET(.04)=""
	 * XURET(.04,"PATIENT")=""
	 * XURET(.05)=".5^POSTMASTER"
	 * XURET(.05,"GENERATED BY")=""
	 * XURET(.06)="1^YES"
	 * XURET(.06,"GENERATED WHILE QUEUED")=""
	 * XURET(.07)=""
	 * XURET(.07,"STATUS")=""
	 * XURET(.08)=""
	 * XURET(.08,"RETENTION DATE")=""
	 * XURET(1.01)="Lab Messaging error #37 on message #416570"
	 * XURET(1.01,"DISPLAY TEXT")=""
	 * XURET(1.02)=""
	 * XURET(1.02,"OPTION FOR PROCESSING")=""
	 * XURET(1.03)="DIS"
	 * XURET(1.03,"ROUTINE TAG")=""
	 * XURET(1.04)="LA7UXQA"
	 * XURET(1.04,"ROUTINE FOR PROCESSING")=""
	 * XURET(2)=416570
	 * XURET(2,"DATA FOR PROCESSING")=""
	 * XURET(3.01)=""
	 * XURET(3.01,"GUID FOR GUI")=""
	 * XURET(4)=""
	 * XURET(4,"LONG INFO TEXT")=""
	 *
	 */
	@Test
	@Ignore
	public void testAlertDat001() throws VistaWebServiceFault {
	//TODO: Setup Test Case when reported RPC issues are resolved (Leisa)
	ArrayList <String> results = new ArrayList <String>();
	results.add("LA7-MESSAGE-416570;.5;3030226.111106");


		request.setXuaID("LA7-MESSAGE-416570;.5;3030226.111106");

		// Execute request against mocked object backend.
		response = service.alertDat(request);

		assertNotNull(response);
		assertEquals(results.get(0), response.getDataList().get(0));
	}
	/**
	 * Test Case #2  
	 * 
	 *  In this test case you will look for an alert that does not exist.  No data is returned.
	 *	
	 *	>S XURET="",XUAID="LA7-MESSAGE-DAGGAG;.5;3030226.111106"
	 *
	 *	>D ALERTR^XUSOAR(XURET,XUAID)
	 *
	 *	>ZW XURET
	 *	XURET=””
	 *
	 * @throws VistaWebServiceFault
	 */
	@Test
	@Ignore
	public void testAlertDat002() throws VistaWebServiceFault {
	//TODO: Setup Test Case when reported RPC issues are resolved (Leisa)
	ArrayList <String> results = new ArrayList <String>();
		results.add("");
	
	
		request.setXuaID("");
	
		// Execute request against mocked object backend.
		response = service.alertDat(request);
	
		assertNotNull(response);
		assertEquals(results.get(0), response.getDataList().get(0));
	}

}
